
############################

d/lambda should be nan for bulk

#####
if it is possible to use json.dumps instead pd.to_json to save df. Latter convert inf to null.



####################################
/home/janus/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1404: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)
2020-11-30 21:07:44,567 - __main__ - ERROR - 7207 - Exceptiion error
Traceback (most recent call last):
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/rheoQCM.py", line 1409, in <lambda>
    self.ui.actionRegenerate_allref.triggered.connect(lambda: self.regenerate_from_raw(chn_name='ref', mode='all'))
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/rheoQCM.py", line 3044, in regenerate_from_raw
    self.data_refit(chn_name, sel_idx_dict, regenerate=True)
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/rheoQCM.py", line 7046, in data_refit
    self.update_mpl_plt12()
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/rheoQCM.py", line 3214, in update_mpl_plt12
    self.update_mpl_dataplt(plt_str='plt1')
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/rheoQCM.py", line 3288, in update_mpl_dataplt
    harm_ydata = self.get_harm_data_by_typestr(plt_opt[0], plt_chnname, plt_harm, mark=mark, unit_t=timeuint, unit_temp=tempunit)
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/rheoQCM.py", line 3452, in get_harm_data_by_typestr
    data = self.data_saver.get_marked_harm_col_from_list_column(chn_name, harm, 'fs', deltaval=True, norm=True, mark=mark)
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 1350, in get_marked_harm_col_from_list_column
    cols = self.get_list_column_to_columns(chn_name, col, mark=False, deltaval=deltaval, norm=norm) # get all data
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 1588, in get_list_column_to_columns
    s = self.convert_col_to_delta_val(chn_name, col, norm=norm)
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 1694, in convert_col_to_delta_val
    self.set_ref_set(chn_name, *self.exp_ref[chn_name + '_ref'])
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 1885, in set_ref_set
    self.copy_to_ref(chn_name, df.loc[idx_list_opened, :]) # copy to reference data set
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 1815, in copy_to_ref
    df = self.reset_match_marks(df, mark_pair=(0, 1)) # mark 1 to 0
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 2388, in reset_match_marks
    df_new.marks = df_new.marks.apply(lambda x: [new_mark if mark == old_mark else mark for mark in x])
  File "/home/janus/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 4038, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2227, in pandas._libs.lib.map_infer
  File "/home/janus/Documents/FS/zhczq_repo/rheoQCM/tests/modules/DataSaver.py", line 2388, in <lambda>
    df_new.marks = df_new.marks.apply(lambda x: [new_mark if mark == old_mark else mark for mark in x])
TypeError: 'float' object is not iterable
UI error occured.